# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QMapPermalinkDialog
                                 A QGIS plugin
 Navigate QGIS map views through external permalink system
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by yamamoto-ryuzo
        email                : 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QDialog

# UIファイルのパスを指定
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'qmap_permalink_dialog_base.ui'))


class QMapPermalinkDialog(QDialog, FORM_CLASS):
    """QMapPermalinkのダイアログクラス
    
    Qt Designerで作成されたUIファイルを読み込んで表示する
    """
    
    def __init__(self, parent=None):
        """コンストラクタ
        
        Args:
            parent: 親ウィジェット
        """
        super(QMapPermalinkDialog, self).__init__(parent)
        # UIを設定
        self.setupUi(self)